### ISSUE TITLE
image rendering broken with phpthumbof

### ISSUE THREAD

**Issue by rtripault** [Bruno17/multiItemsGridTV#4]
While using a TV type as image in the grid, the preview/thumbnail rendering/creating is broken if phpthumbof is installed.

Edit: it might be related to this bug (http://bugs.modx.com/issues/3197) and not phpthumbof

**Comment by twincreekmedia** [comment]
Cause of the problem seems to be "filemanager_path" and "filemanager_url" in the system settings. If the filemanager path is set to anything other than the root, and the filemanager url is set to that path as well, the thumbnails don't display. Remove the filemanager url and the thumbs are fine - problem: tiny mce image upload needs that url to be set.

Example:
Thumbnails work, but other images won't work:
filemanager_path: assets/uploads/
filemanager_url: <blank>

Thumbnails don't work, but everything else does (imageTV included!)
filemanager_path: assets/uploads/
filemanager_url: assets/uploads/

Tested on MODx 2.0.7-pl
